name: enum_object
description: Converts enum value to String and vice versa
version: 0.0.1
homepage: https://github.com/EddieKamau/enum_object

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
